config/routes.rb
Cheesecake::Application.routes.draw do

  devise_for :admins

  root to: "home#index"
  match "contact" => 'contacts#new'
  resources :news
  # other routes go here
  resources :comics do
    member do
      get ':slug' => 'comics#show'
    end
    resources :comic_pages

  end
  resources :illustrations
  resources :artists
  
  namespace :backend do
    root to: "comics#index"
    resources :artists
    resources :admins
    resources :news
    resources :illustrations
    resources :comics do
      resources :chapters do
        resources :comic_pages
      end
    end
  end

end

app/models/comic.rb
class Comic < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  attr_accessible :description, :front_page, :title, :slug, :artists, :website, :artist_ids
  has_and_belongs_to_many :artists
  accepts_nested_attributes_for :artists
  validates_presence_of :title, :slug
  validates_uniqueness_of :title, :slug
  before_destroy :artist_connection_delete
  has_many :chapters

  attr_accessible :front_page
  has_attached_file :front_page, :styles => { :home => "360x548>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"

  #mount_uploader :front_page, FrontPageUploader
  def artist_connection_delete
    artists.clear
  end
end

app/models/comic_view.rb
class ComicView < ActiveRecord::Base
  attr_accessible :comic_id, :ip
  validates_presence_of :ip, :comic_id
end

app/controllers/backend/admins_controller.rb
class Backend::AdminsController < Backend::ResourceController
  def create
    @admin = Admin.new(params[:admin]) 
    if @admin.save
      redirect_to backend_admins_path
    else
      flash[:alert] = "Please fill in all the fields and make sure password and the confirmation are the same."
      render :new
    end
  end
end

app/controllers/backend/application_controller.rb
class Backend::ApplicationController < ActionController::Base
  before_filter :authenticate_admin!
  protect_from_forgery
  layout 'backend'
end

app/controllers/backend/artists_controller.rb
class Backend::ArtistsController < Backend::ResourceController
	def create
		@artist = Artist.new(params[:artist])
		if @artist.save
			flash[:notice] = "Artist created!"
			redirect_to backend_artist_path(@artist)
		else
			flash[:alert] = "Something went wrong!"
			render :new
		end
	end
end

app/controllers/backend/chapters_controller.rb
class Backend::ChaptersController < Backend::ResourceController
  def new
    @comic = Comic.where(:slug => params[:comic_id]).first
    @chapter = Chapter.new(comic_id: @comic.id)
  end

  def show
    @comic = Comic.find(params[:comic_id])
    @pages = ComicPage.where(chapter_id: params[:id]).order(:page_order)
    @chapter = Chapter.find(params[:id])
  end

  def edit
    @comic = Comic.where(:id => params[:comic_id]).first
    @chapter = Chapter.find(params[:id])
  end

  def create
    @chapter = Chapter.new
    @comic = Comic.where(:slug => params[:comic_id]).first
    @chapter.comic_id = @comic.id
    @chapter.title = params[:chapter][:title]
    if @chapter.save
      flash[:notice] = "Chapter saved successfully"
      redirect_to backend_comic_chapter_path(@chapter, comic_id: @comic.slug)
    else
      flash[:alert] = "Not saved!"
      render :new
    end
  end

  def update
    @chapter = Chapter.find(params[:id])
    @comic = Comic.where(:slug => params[:comic_id]).first
    @chapter.comic_id = @comic.id
    @chapter.title = params[:chapter][:title]
    if @chapter.save
      flash[:notice] = "Chapter saved successfully"
      redirect_to backend_comic_chapter_path(@chapter, comic_id: @comic.slug)
    else
      flash[:alert] = "Not saved!"
      render :edit
    end
  end
end

app/controllers/backend/comic_pages_controller.rb
class Backend::ComicPagesController < Backend::ApplicationController
	def new
    @comic_page = ComicPage.new(chapter_id: params[:chapter_id])
    @chapter = Chapter.find(params[:chapter_id])
  end

  def create
    @comic_page = ComicPage.new(chapter_id: params[:chapter_id])
    @chapter = @comic_page.chapter
    @comic_page.comic_page_image = params[:comic_page][:comic_page_image]
    @comic_page.page_order = params[:comic_page][:page_order]
    if @comic_page.save
      flash[:notice] = "Page saved!"
      redirect_to backend_comic_chapter_path(:comic_id => @comic_page.chapter.comic.id, :id => @comic_page.chapter.id)
    else
      flash[:alert] = "Not saved!"
      render :new
    end
  end

  def edit
    @comic_page = ComicPage.find(params[:id])
    @chapter = Chapter.find(params[:chapter_id])
  end

  def update
    @comic_page = ComicPage.find(params[:id])
    @comic_page.comic_page_image = params[:comic_page][:comic_page_image]
    @comic_page.page_order = params[:comic_page][:page_order]
    if @comic_page.save
      flash[:notice] = "Page saved!"
      redirect_to backend_comic_chapter_path(:comic_id => @comic_page.chapter.comic.id, :id => @comic_page.chapter.id)
    else
      flash[:alert] = "Not saved!"
      render :new
    end
  end


end

app/controllers/backend/comics_controller.rb
class Backend::ComicsController < Backend::ResourceController
	def create	
		@comic = Comic.new
		@comic.artist_ids = Artist.where(id: params[:comic][:artists])
		@comic.title = params[:comic][:title]
		@comic.website = params[:comic][:website]
		@comic.description = params[:comic][:description]
		@comic.slug = params[:comic][:slug]
		@comic.front_page = params[:comic][:front_page]
		puts @comic.inspect
		if @comic.save
			flash[:notice] = "Comic created!"
			redirect_to backend_comic_path(@comic)
		else
			flash[:alert] = @comic.errors.inspect
			render :new
		end
	end

	def update
		@comic = Comic.find(params[:id])
    @comic.update_attributes(params[:comic])
		if @comic.save
			flash[:notice] = "Comic updated!"
			redirect_to backend_comic_path(@comic)
		else
			flash[:alert] = @comic.errors.inspect
			render :new
		end
	end
end

app/controllers/backend/illustrations_controller.rb
class Backend::IllustrationsController < Backend::ResourceController
  def create
		@illustration = Illustration.new(params[:illustration])
		if @illustration.save
			flash[:notice] = "Illustration created!"
			redirect_to backend_illustrations_path
		else
			flash[:alert] = @illustration.errors.inspect
			render :new
		end
	end

	def update
		@illustration = Illustration.find(params[:id])

		if @illustration.update_attributes(params[:illustration])
			flash[:notice] = "Illustration updated!"
			redirect_to backend_illustrations_path
		else
			flash[:alert] = @illustration.errors.inspect
			render :new
		end
	end

end

app/controllers/backend/news_controller.rb
class Backend::NewsController < Backend::ResourceController
end

app/controllers/backend/resource_controller.rb
class Backend::ResourceController < Backend::ApplicationController
  inherit_resources
  respond_to :html
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  layout 'comics'
	
  def show
		@comic = Comic.where(slug: params[:id]).first
	end

  def index
    @comics = Comic.all
  end
    
end

app/helpers/backend/application_helper.rb
module Backend::ApplicationHelper
end

app/helpers/backend/artists_helper.rb
module Backend::ArtistsHelper
end

app/helpers/backend/chapters_helper.rb
module Backend::ChaptersHelper
end

app/helpers/backend/comic_pages_helper.rb
module Backend::ComicPagesHelper
end

app/helpers/backend/comics_helper.rb
module Backend::ComicsHelper
end

app/helpers/backend/illustrations_helper.rb
module Backend::IllustrationsHelper
end

app/helpers/backend/news_helper.rb
module Backend::NewsHelper
end

app/helpers/backend/resource_helper.rb
module Backend::ResourceHelper
end

app/views/backend/comics/_form.html.haml
=form_for [:backend, @comic] do |f|
  .control-group
    =f.label :title, :class => "control-label"
    .controls
      =f.text_field :title
  .control-group
    =f.label :website, :class => "control-label"
    .controls
      =f.text_field :website
  .control-group
    =f.label :description, :class => "control-label"
    .controls
      =f.text_area :description
  .control-group
    =f.label :artists, :class => "control-label"
    .controls
      =f.select :artist_ids, options_from_collection_for_select(Artist.all, 'id', 'name'), {multiple: true}
  .control-group
    =f.label :front_page, :class => "control-label"
    .controls
      =f.file_field :front_page
  .form-actions
    =f.submit :class => "btn btn-primary"

app/views/backend/comics/edit.html.haml
=render :partial => 'form'

app/views/backend/comics/index.html.haml
%h1 Comics

%table.table.table-striped.table-bordered
	%tr
		%th Comicname
		%th Comicslug
		%th Options

	- @comics.each do |comic|
		%tr
			%td=link_to comic.title, backend_comic_path(comic)
			%td=comic.slug
			%td
				=link_to "Edit", edit_backend_comic_path(comic), class: "btn btn-mini btn-success"
				=link_to "Delete", backend_comic_path(comic), :method => :delete, class: "btn btn-mini btn-danger"
=link_to 'Nieuw', new_backend_comic_path, :class => "btn btn-primary btn-large"

app/views/backend/comics/new.html.haml
= render :partial => 'form'

app/views/backend/comics/show.html.haml
%h1=@comic.title
%h3.sub-title Chapters

%table.table.table-striped.table-bordered
  %tr
    %th Chapter
    %th

  - @comic.chapters.each do |chapter|
    %tr
      %td
        View chapter:
        =link_to chapter.title, backend_comic_chapter_path(chapter.id, :comic_id => chapter.comic.slug)
      %td
        =link_to "Edit", edit_backend_comic_chapter_path(id: chapter.id, comic_id: @comic.id)
        =link_to "Delete", backend_comic_chapter_path(chapter_id: chapter.id, comic_id: @comic.id), :method => :delete
    %tr
      %td{colspan: 5} Pages for chapter
    - chapter.comic_pages.each do |page|
      %tr
        %td=page.page_order
        %td=link_to 'Edit', edit_backend_comic_chapter_comic_page_path(comic_id: @comic.id, chapter_id: page.chapter.id, id: page.id)

=link_to 'Nieuw', new_backend_comic_chapter_path(:comic_id => @comic.slug), :class => "btn btn-primary btn-large"