config/routes.rb
Cheesecake::Application.routes.draw do

  devise_for :admins

  root to: "home#index"
  match "contact" => 'contacts#new'
  resources :news
  # other routes go here
  resources :comics do
    member do
      get ':slug' => 'comics#show'
    end
    resources :comic_pages

  end
  resources :illustrations
  resources :artists
  
  namespace :backend do
    root to: "comics#index"
    resources :artists
    resources :admins
    resources :news
    resources :illustrations
    resources :comics do
      resources :chapters do
        resources :comic_pages
      end
    end
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug, use: :slugged
  attr_accessible :description, :firstname, :lastname, :slug, :suffix, :website
  has_and_belongs_to_many :comics
  has_many :news
  validates_presence_of :firstname, :lastname, :slug

  def name
    name = self.firstname + " "
    unless self.suffix.nil?
      name += self.suffix + " "
    end
    name += self.lastname
  end
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  attr_accessible :comic_id, :title
  belongs_to :comic
  validates_presence_of :comic_id
  has_many :comic_pages
end

app/models/comic.rb
class Comic < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  attr_accessible :description, :front_page, :title, :slug, :artists, :website, :artist_ids
  has_and_belongs_to_many :artists
  accepts_nested_attributes_for :artists
  validates_presence_of :title, :slug
  validates_uniqueness_of :title, :slug
  before_destroy :artist_connection_delete
  has_many :chapters

  attr_accessible :front_page
  has_attached_file :front_page, :styles => { :home => "360x548>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"

  #mount_uploader :front_page, FrontPageUploader
  def artist_connection_delete
    artists.clear
  end
end

app/models/comic_page.rb
class ComicPage < ActiveRecord::Base
  attr_accessible :order, :comic_page_image, :chapter_id
  validates_presence_of :page_order, :comic_page_image
  belongs_to :chapter

  attr_accessible :comic_page_image
  has_attached_file :comic_page_image, :styles => { :home => "360x548>", :thumb => "150x214>" }, :default_url => "/images/:style/missing.png"
  def name
    "Page "+self.page_order.to_s
  end
end

app/models/comic_view.rb
class ComicView < ActiveRecord::Base
  attr_accessible :comic_id, :ip
  validates_presence_of :ip, :comic_id
end

app/models/illustration.rb
class Illustration < ActiveRecord::Base
  attr_accessible :artist_id, :description, :image, :title, :artist
  belongs_to :artist
  validates_presence_of :artist_id, :image, :title
  attr_accessible :image
  has_attached_file :image, :styles => {  :thumb => "150x214>"  }, :default_url => "/images/:style/missing.png"
end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :artist_id, :body, :published, :title
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :active, :body, :title
  validates_presence_of :title
  validates_uniqueness_of :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller?
      "backend"
    else
      "application"
    end
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  layout 'comics'
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end
end

app/controllers/comic_pages_controller.rb
class ComicPagesController < ApplicationController
  layout 'gallery'

  def index
    @comic_pages = ComicPages.where(:chapter_id => params[:id])
  end
  
  def show
    @comic = Comic.where(slug: params[:comic_id]).first
    @comic_pages = @comic.chapters.map(&:comic_pages).flatten
    @chapters = @comic.chapters
    @comic_page = ComicPage.find_by_id(params[:id])
    # raise @comic_page.inspect
    if @comic_page.page_order.to_i.odd?
      @rightpage = ComicPage.where(:page_order => @comic_page.page_order+1, :chapter_id => @comic_page.chapter_id).first
      @leftpage = @comic_page
    else
      @leftpage = ComicPage.where(:page_order => @comic_page.page_order-1, :chapter_id => @comic_page.chapter_id).first
      @rightpage = @comic_page
    end
    unless @rightpage == ComicPage.where(chapter_id: @comic_page.chapter_id).last || @rightpage.nil?
      @nextpage = ComicPage.where(chapter_id: @comic_page.chapter_id, :page_order => @rightpage.page_order+1).first
    else
      @nextpage = nil
    end

    unless @leftpage == ComicPage.where(chapter_id: @comic_page.chapter_id).first || @leftpage.nil? 
      @previouspage = ComicPage.where(chapter_id: @comic_page.chapter_id, :page_order => @leftpage.page_order-1).first 
    else 
      @previouspage = nil
    end
  end
    
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  layout 'comics'
	
  def show
		@comic = Comic.where(slug: params[:id]).first
	end

  def index
    @comics = Comic.all
  end
    
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  layout 'comics'
  def new
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'application'
	def index
    @comics = Comic.limit(3)
    @news = News.limit(5)
    @artists = Artist.limit(5)
	end
end

app/controllers/illustrations_controller.rb
class IllustrationsController < ApplicationController
  layout 'comics'
  def index
    @illustrations = Illustration.all
  end

  def show
    @illustrations = Illustration.find_by_id(params[:id])
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  layout "comics"
  def index
    @news = News.page(params[:page]).per(10)
  end
  def show
    @news = News.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backend/news_helper.rb
module Backend::NewsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/common/_footer.html.haml
.container{style: 'width: 1200px;'}
  .row
    .span12.copyright
      %p &copy; 2012 Cheesecake Studios - Powered by SpaceSquared/Omnidimensional
    .span12.links
      %span=link_to 'Home', root_path
      |
      %span=link_to 'News', news_index_path
      |
      %span=link_to 'Comics', comics_path
      |
      %span=link_to 'Artists', artists_path
      |
      %span=link_to 'Contact', '#'

:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-34281301-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/common/_menu.html.haml
%ul#menu.nav
  %li
    %a{:href=> comics_url}
      %h1 Read
      .subtext
        our comics
  %li
    %a{:href=> artists_url}
      %h1 Meet
      .subtext
        our artists
  %li
    %a{:href=> illustrations_url}
      %h1 Check
      .subtext
        our prints

app/views/common/_sidebar.html.haml
#sidebar
  #about.well
    %h3 About us
    %p CheeseCake! Studio was founded in 2004 and is still creating cool underground comics in manga influenced style. Next to that, it's one of the oldest Doujinshi groups of the Netherlands. 

    %p Next to that they're pretty whacky, loud and drunk on comic/anime conventions so they can be quite scary. But they're very sweet on the inside, just like a CheeseCake ♥!

  %ul.nav.nav-list.well
    %li
      =link_to 'Artists', artists_path
    %li
      =link_to 'Comics', comics_path
    %li
      =link_to 'Illustrations', illustrations_path
    %li.divider
      Where you also can find us
    %li
      =link_to 'J-Pop Foundation', 'http://www.jpop-foundation.com/', target: :blank
    %li
      =link_to 'Animecon', 'http://www.animecon.nl/', target: :blank